### ISSUE TITLE
Typo maybe?! polarmode

### ISSUE THREAD

**Issue by Hassankh92** [znasipak/pybhpt#4]
https://github.com/znasipak/pybhpt/blob/e2354353061328e127ed9ca05c77018a631e6945/pybhpt/teuk.py#L26C22-L26C23

**Comment by znasipak** [comment]
Yes this was definitely a typo. It was fixed with the recent merge #6

**Comment by znasipak** [comment]
Yes this was definitely a typo. It was fixed with the recent merge https://github.com/znasipak/pybhpt/pull/6
